name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # macos-10.15 stuck on: Waiting for a runner to pick up this job...
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Cache NodeJS
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nodejs-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-nodejs-
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Restore Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/src-tauri/.cargo/bin/
            ~/src-tauri/.cargo/registry/index/
            ~/src-tauri/.cargo/registry/cache/
            ~/src-tauri/.cargo/git/db/
            ~/src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: install app dependencies and build it
        run: yarn && yarn build

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
